### PR TITLE
change the time zone to 'US/Eastern' to show the check date in pages correctly

### PR DESCRIPTION
**Pull request by zhangmingda**

### CODE REVIEW

**Comment by zhangmingda** [comment]
image

This may relate to changing time zone setting. I will check this.

**Comment by capooti** [comment]
I don't think this is the case. I will re-trigger the build and see if we get green. Sometime the build seems to fail for undetermined reasons

**Comment by zhangmingda** [comment]
Thanks. @capooti

**Comment by capooti** [comment]
Is US/Eastern string format different than from UTC? I though it is just the time (5 hours gap between the two). @tomkralidis what do you think?

**Comment by capooti** [comment]
@tomkralidis in that case I think we should create the strings from datetime object in tests. So they will work whatever is the TIME_ZONE setting

**Comment by zhangmingda** [comment]
When we set USE_TZ=True and TIME_ZONE = 'US/Estern', the date built by 'datetime.datetime()' will be transferred from 'US/Estern' to 'UTC' when stored in the database. But, when we retrieve the date again, it always returns the UTC date. That's maybe why 5 hours gap exists. Maybe, we can set the time zone when using  'datetime.datetime()'. I will try this.

**Comment by capooti** [comment]
I don't think there is the need to set the time zone when using datetime.datetime() to create the date. It should be automatically set from settings. The problem is that in tests the date string are not created starting from the datetime library I think.

**Comment by zhangmingda** [comment]
Continue to use UTC.

**Comment by capooti** [comment]
well, it is a bug. Maybe let's file another ticket, something like: "Test fails when changing TIME_ZONE"?

**Comment by zhangmingda** [comment]
Sure. I will work on it. :)

**Pull request closed without merging**
