### PR TITLE
make tests work when changing TIME_ZONE and set TIME_ZONE to US/Eastern - issue#303

### PR DESCRIPTION
**Pull request by zhangmingda**

### CODE REVIEW

**Comment by capooti** [comment]
great!
Please could you leave UTC as default for TIME_ZONE in settings.py, and make it changeable using an environment variable? thanks!
@tomkralidis could you also give a look?

**Comment by zhangmingda** [comment]
Sure. I will change it back to UTC right now.

**Comment by capooti** [comment]
thanks @zhangmingda

**Comment by zhangmingda** [comment]
Thanks for the hints and merge. @capooti

**Comment by tomkralidis** [comment]
+1 thanks @zhangmingda

**Pull request merged**
